## 13) More NumPy Plus Linear Algebra Fundamentals

Related references:

- https://jakevdp.github.io/PythonDataScienceHandbook/02.04-computation-on-arrays-aggregates.html
- https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html
- [Feature Engineering for Machine Learning](https://search.lib.umich.edu/catalog/record/016260792) 
- [The Manga Guide to Linear Algebra](https://www.safaribooksonline.com/library/view/the-manga-guide/9781457166730/)
- [Introduction to Linear Algebra by Gilbert Strang](http://math.mit.edu/~gs/linearalgebra/)

## The simplicity of NumPy math

As we've discussed, Numpy allows us to perform math with arrays without writing loops, speeding programs and programming. 

As always, array sizes must be compatible. Binary operations are performed on an element-by-element basis:

In [1]:
import numpy as np

a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
print(a + b)
print(a * b)

[5 6 7]
[ 0  5 10]


### Broadcasting

We can also perform these operations with a scalar; NumPy will "broadcast" it to the correct size for the binary operation. In the case below, it will treat `5` as the ndarray `[5, 5, 5]` while never actually creating such an array.

In [2]:
print(a + 5)
print(a * 5)

[5 6 7]
[ 0  5 10]


`Broadcasting` can also be done in higher dimensions:

In [3]:
m = np.ones((3, 3))
m + a

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

In [4]:
print(a)
print(b.reshape((3, 1)))

[0 1 2]
[[5]
 [5]
 [5]]


In [5]:
a + b.reshape((3, 1))

array([[5, 6, 7],
       [5, 6, 7],
       [5, 6, 7]])

A visual to describe broadcasting:

![From PythonDataScienceHandbook](images/lect13_broadcasting.png)

The light boxes represent the broadcasted values: again, this extra memory is not actually allocated in the course of the operation, but it can be useful conceptually to imagine that it is.

### More examples of NumPy's math knowledge

In [6]:
x = [1, 2, 4, 10]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))
print("sum(x)   =", np.sum(x))
print("min(x)   =", np.min(x))
print("max(x)   =", np.sum(x))
print("mean(x)  =", np.mean(x))
print("std(x)   =", np.std(x))

x     = [1, 2, 4, 10]
e^x   = [  2.71828183e+00   7.38905610e+00   5.45981500e+01   2.20264658e+04]
2^x   = [    2.     4.    16.  1024.]
3^x   = [    3     9    81 59049]
ln(x)    = [ 0.          0.69314718  1.38629436  2.30258509]
log2(x)  = [ 0.          1.          2.          3.32192809]
log10(x) = [ 0.          0.30103     0.60205999  1.        ]
sum(x)   = 17
min(x)   = 1
max(x)   = 17
mean(x)  = 4.25
std(x)   = 3.49106001094


### What about math with NaNs?

NaN = not a number, and you can specify NaN with np.nan.

In [7]:
m = np.random.random((3, 4))
n = np.random.random((4, 3))
m[2, 3] = np.nan
print(m)

[[ 0.80112465  0.78693847  0.28087913  0.5076622 ]
 [ 0.98987765  0.42932083  0.11248431  0.59235153]
 [ 0.92880657  0.59126631  0.69073153         nan]]


In [8]:
m + n.T

array([[ 1.0344498 ,  1.53628788,  0.85610662,  1.44420146],
       [ 1.46308366,  1.4169669 ,  0.12063538,  1.35875076],
       [ 1.30389843,  1.35908355,  1.23925237,         nan]])

In [9]:
m * n.T

array([[ 0.18692253,  0.58969188,  0.1615694 ,  0.47544558],
       [ 0.46841605,  0.42401703,  0.00091687,  0.45397775],
       [ 0.34838778,  0.45398447,  0.37888064,         nan]])

Let's check if these other functions work with `np.nan`:

In [10]:
print("m     =", m)
print("e^m   =", np.exp(m))
print("2^m   =", np.exp2(m))
print("3^m   =", np.power(3, m))
print("ln(m)    =", np.log(m))
print("log2(m)  =", np.log2(m))
print("log10(m) =", np.log10(m))
print("sum(m)   =", np.sum(m))
print("min(m)   =", np.min(m))
print("max(m)   =", np.max(m))
print("mean(m)  =", np.mean(m))
print("std(m)   =", np.std(m))

m     = [[ 0.80112465  0.78693847  0.28087913  0.5076622 ]
 [ 0.98987765  0.42932083  0.11248431  0.59235153]
 [ 0.92880657  0.59126631  0.69073153         nan]]
e^m   = [[ 2.22804529  2.19666098  1.32429353  1.66140263]
 [ 2.69090521  1.53621381  1.1190547   1.80823553]
 [ 2.53148623  1.80627427  1.99517452         nan]]
2^m   = [[ 1.74245892  1.7254091   1.214935    1.42174448]
 [ 1.98601655  1.34659949  1.08108826  1.50770223]
 [ 1.90370057  1.50656854  1.61410175         nan]]
3^m   = [[ 2.41120201  2.37391449  1.3614867   1.74669239]
 [ 2.96682319  1.6026478   1.13153673  1.91700614]
 [ 2.77429959  1.91472198  2.13581038         nan]]
ln(m)    = [[-0.22173873 -0.23960522 -1.26983085 -0.67793901]
 [-0.01017393 -0.84555079 -2.18494154 -0.52365503]
 [-0.07385477 -0.52548876 -0.37000406         nan]]
log2(m)  = [[-0.31990136 -0.34567726 -1.83197866 -0.97805924]
 [-0.01467788 -1.21987194 -3.15220432 -0.75547451]
 [-0.10654991 -0.75812002 -0.53380302         nan]]
log10(m) = [[-0.096299

Not all did, but there are "NaN=safe" versions of functions! That is, they ignore the NaNs and carry on.

|Function Name      |   NaN-safe Version  | Description                                      |
|-------------------|---------------------|--------------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                          |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                      |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                         |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                       |
| ``np.var``        | ``np.nanvar``       | Compute variance                                 |
| ``np.min``        | ``np.nanmin``       | Find minimum value                               |
| ``np.max``        | ``np.nanmax``       | Find maximum value                               |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                      |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                      |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                       |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements        |
| ``np.any``        | N/A                 | Evaluate whether any elements are true (see note)|
| ``np.all``        | N/A                 | Evaluate whether all elements are true (see note)|
| N/A               | ``np.isnan``        | Test for NaN; returns a boolean array            |

*Note*:  NaN, positive infinity and negative infinity evaluate to True because these are not equal to zero.

In [11]:
print("sum(m)   =", np.nansum(m))
print("min(m)   =", np.nanmin(m))
print("max(m)   =", np.nanmax(m))
print("mean(m)  =", np.nanmean(m))
print("std(m)   =", np.nanstd(m))

sum(m)   = 6.71144316762
min(m)   = 0.112484309743
max(m)   = 0.989877645554
mean(m)  = 0.610131197057
std(m)   = 0.255826773406


These are a few examples, but just ask the Internet if there is anything you need and you'll get an answer, even if that is to use `scipy.special` as we had to for `erfc`. Let's focus on a particular kind of math NumPy knows well: linear algebra.

## Linear algebra

### Overview

![What is linear algebra](images/lect13_linear-alg.png)
This and other comics from [The Manga Guide to Linear Algebra](https://www.safaribooksonline.com/library/view/the-manga-guide/9781457166730/)

Importantly, they are great for solving linear equations, especially those with the same number unknowns and independent equations. They are great for turning problems into forms that are easily solved by computers!

![What is linear algebra](images/lect13_linear-alg-overview.png)

### Fundamentals

#### Inverse Functions

![Functions](images/lect13_onto-one2one.png)
![Functions](images/lect13_inverse.png)

#### Linear Transformations

Let $x_i$ and $x_j$ be two arbitrary elements of the set $X$, $c$ be any real number, and $f$ be a function from $X$ to $Y$. $f$ is called a *linear transformation* from $X$ to $Y$ if is satisfies both:

1. $f(x_i) + f(x_j) = f(x_i + x_j)$
1. $cf(x_i) = f(cx_i)$

![Functions](images/lect13_linear-trans.png)

#### Permutations

Choosing three from n items in a certain order creates a permutation of the chosen items. The number of possible permutations of k objects chosen among n objects is written as: 
$ _nP_k $
The number of ways k objects can be chosen among n possible ones is equal to:
$$ _nP_k = \frac{n!}{(n-k)!} $$

#### Combinations

Choosing k among n items without considering the order in which they are chosen is called a combination. The number of different ways this can be done is written by using the binomial coefficient notation:
$ {n\choose k} $ or $_nC_r$
which is read "n choose k."

$$ {n\choose k} = \frac{n!}{k!(n-k)!} = \frac{_nP_k}{k!} $$

When the order *doesn't* matter, it is a Combination.

When the order *does* matter it is a Permutation.
![Basics](images/lect13_permutation.png)
A Permutation is an ordered Combination.

## Matrices

![Matrices](images/lect13_matrix.png)
![Matrices](images/lect13_matrix1.png)
![Matrices](images/lect13_matrix2.png)
![Matrices](images/lect13_matrix3.png)
![Matrices](images/lect13_matrix4.png)
![Matrices](images/lect13_matrix5.png)
![Matrices](images/lect13_matrix6.png)

### Matrix Addition

![Matrices](images/lect13_matrix7.png)

In [12]:
a = np.array([[10, 10]])
b = np.array([[3, 6]])
print(a, b)

[[10 10]] [[3 6]]


In [13]:
print(a - b)

[[7 4]]


### Scalar Multiplication

![Matrices](images/lect13_matrix8.png)

In [14]:
c = np.arange(1, 7).reshape((3, 2))
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
print(10 * c)

[[10 20]
 [30 40]
 [50 60]]


### Matrix Multiplication

![Matrices](images/lect13_matrix9.png)

In [16]:
d = np.array([[8, -3], [2, 1]])
e = np.array([[3, 1], [1, 2]])
print(d)
print(e)

[[ 8 -3]
 [ 2  1]]
[[3 1]
 [1 2]]


In [17]:
print(d * e)
print(np.multiply(e, d))

[[24 -3]
 [ 2  2]]
[[24 -3]
 [ 2  2]]


In [18]:
np.matmul(d, e)

array([[21,  2],
       [ 7,  4]])

In [19]:
np.matmul(e, d)

array([[26, -8],
       [12, -1]])

![Matrices](images/lect13_matrix10.png)

### Special Matrices

![Matrices](images/lect13_matrix11.png)

![Matrices](images/lect13_matrix12.png)

In [20]:
f = np.array([[2, 0], [0, 3]])
print(f)

[[2 0]
 [0 3]]


In [21]:
np.linalg.matrix_power(f, 3)

array([[ 8,  0],
       [ 0, 27]])

![Matrices](images/lect13_matrix13.png)

#### What is the identity matrix and why is it called that?

In [22]:
eye = np.eye(2, dtype=int)
print(d)
print(eye)

[[ 8 -3]
 [ 2  1]]
[[1 0]
 [0 1]]


In [23]:
np.matmul(d, eye)

array([[ 8, -3],
       [ 2,  1]])

In [24]:
np.matmul(eye, d)

array([[ 8, -3],
       [ 2,  1]])

![Matrices](images/lect13_matrix14.png)

If the product of two square matrices is an identity matrix, then the two factor matrices are inverses of each other. This means that 
$ \left( \begin{array}{ccc}
x_{11} & x_{12} \\
x_{21} & x_{22} \end{array} \right) $ is an inverse matrix to 
$ \left( \begin{array}{ccc}
1 & 2 \\
3 & 4 \end{array} \right) $  if

$$ \left( \begin{array}{ccc}
1 & 2 \\
3 & 4 \end{array} \right)
\left( \begin{array}{ccc}
x_{11} & x_{12} \\
x_{21} & x_{22} \end{array} \right)
= \left( \begin{array}{ccc}
1 & 0 \\
0 & 1 \end{array} \right) $$

![Matrices](images/lect13_matrix15.png)

![Matrices](images/lect13_matrix16.png)

![Matrices](images/lect13_matrix17.png)

Now, using Gaussian elimination (e.g. the sweeping method) find, the inverse matrix of 
$ \left( \begin{array}{ccc}
3 & 1 \\
1 & 2 \end{array} \right) $

In [25]:
g = np.array([[3, 1], [1, 2]])
h = np.linalg.inv(g)
print(h)

[[ 0.4 -0.2]
 [-0.2  0.6]]


In [26]:
# checking our work
np.matmul(g, h)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [27]:
np.matmul(h, g)

array([[ 1.,  0.],
       [ 0.,  1.]])

![Matrices](images/lect13_matrix18.png)

![Matrices](images/lect13_matrix19.png)

![Matrices](images/lect13_matrix20.png)

### Calculating determinants

From: https://www.mathsisfun.com/algebra/matrix-determinant.html
![Matrices](images/lect13_matrix21.png)

In [28]:
k = np.array([[4, 6], [3, 8]])
np.linalg.det(k)

14.000000000000004

![Matrices](images/lect13_matrix22.png)

In [29]:
m = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])
print(m)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]


In [30]:
np.linalg.det(m)

-306.0

![Matrices](images/lect13_matrix23.png)

## Next up: Vectors!